### ISSUE TITLE
Support string based entity resolution

### ISSUE THREAD

**Issue by volak** [volak/Aggregates.NET#20]
Currently we use the full namespace in part of the eventstream name for events and entities.
It would be better to allow a attribute annotation to "name" the event or entity for cases when a refactor affects the namespaces we expect to continue to exist.

This will also help with another feature I'm planning #21

**Comment by Narvalex** [comment]
That approach works for me, as [you can see here](https://github.com/Narvalex/Eventing/blob/Eventing-v1.0.0/src/Sample/Inventory.Domain/InventoryItem.cs)
