### ISSUE TITLE
External state object

### ISSUE THREAD

**Issue by volak** [volak/Aggregates.NET#21]
Entities can really be divided into 2 operations, reading and writing.  

Only 1 entity should be opened for writing, whereas many entities can be opened for reading.  To more easily define and enforce this best-practice we can support a "State" object which can be read from the store and hydrated but cannot raise new events.

The idea being when an entity is defined the user will define the read and write side separately and entities that depend on information in other entities will receive access to the state of the entity not the entity itself.

**Comment by Narvalex** [comment]
I am aggree with you, and that approach [looks cleaner as you can see here](https://github.com/Narvalex/Eventing/blob/Eventing-v1.0.0/src/Sample/Inventory.Domain/InventoryItemService.cs)

**Comment by volak** [comment]
Yes, something more like [this model too](https://github.com/MacLeanElectrical/servicestack-eventstore/tree/master/samples/Samples.WriteModel/Samples.WriteModel/Aggregate)

**Comment by volak** [comment]
Fixed in [v0.11.0](https://github.com/volak/Aggregates.NET/commit/2f21467ebd4c7bd7ede80580810510d73026c256)
