### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by Narvalex** [volak/Aggregates.NET#23]
Please, add some unit tests to the library. This will make easier to try the features and watch the library in action

**Comment by volak** [comment]
:+1: Has been an issue for a while, I have some basic tests which verify behavior but what it really needs is some integration tests for examples.  Still haven't figured out the best way to integration test.

There's some samples here https://github.com/volak/Aggregates.NET/tree/master/src/Samples

**Comment by Narvalex** [comment]
Thanks!
