### ISSUE TITLE
Consider adding `ConfigureAwait(false)`

### ISSUE THREAD

**Issue by danielmarbach** [volak/Aggregates.NET#7]
Quickly glanced at your code and realized that you are not using `[ConfigureAwait(false)`](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) in the behaviors. Strictly speaking it is not required because NSB makes sure that we consistently apply it to all `await` in the pipeline. But I suggest you stay here with the best practice.

**Comment by volak** [comment]
I did notice a lot of that in the new NSB codebase - I am not 100% sure exactly what it does yet but it seems like it messes with how the async context works.  
There is 1 non-critical place I actually do use AsyncLocal - it seems that may be affected here but I'll do some testing to find out for sure

Thanks

**Comment by danielmarbach** [comment]
It should work even with ConfigureAwait(false). See https://github.com/danielmarbach/async-dolls/blob/66c21164292f705822dcbfcd3ce77597f02eb226/async-dolls/6-AsyncStateWithDolls/Script.cs#L19On September 27, 2016 at 10:19 AM Charles Solar <notifications@github.com> wrote:I did notice a lot of that in the new NSB codebase - I am not 100% sure exactly what it does yet but it seems like it messes with how the async context works. There is 1 non-critical place I actually do use AsyncLocal - it seems that may be affected here but I'll do some testing to find out for sureThanks—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
